version: "3.0"
services:
  fpm:
    image: fezzz/php-fpm
    restart: always
    privileged: true
    volumes:
      - .:/web
    environment:
      APP_ENV: docker
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./:/web
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2000:80
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: admin_oa
